package goAba

import (
	"fmt"
	"time"
)

type Header struct {
	Type        string    // should be "0"
	BSB         string    // Main account BSB. Ignored according to spec
	Account     string    // Main account number, Up to 9 chars, ignored
	Bank        string    // Name of Financial institution processing the file, 3 char "ANZ", "WBC"
	User        string    // How the user will be shown in the transactions of the 3rd party banks
	UserNumber  string    // The ID of the user supplying this file
	Description string    // Description of this file entries, up to 12 chars
	Date        string    // date to be processed
	Time        time.Time // time to be processed, ignored.
}

type SchemaField struct {
	Name       string
	Boundaries []int
	Type       string
}

type Schema struct {
	RecordType string
	Fields     []SchemaField
}

type Footer struct {
	Type                 string // Default = "7", auto generated field, can override
	BSB                  string // Default = "999999" This is autogenerated, can override
	NetTotal             string // This is auto generated, can overide
	CreditTotal          string // This is auto generated, can override
	DebitTotal           string // this is auto generated, can override
	NumberOfTransactions string // this is autog generated, can override
}

type Transaction struct {
	TransactionType string  //
	BSB             string  // the 3rd party account BSB
	Tax             string  //
	TransactionCode string  // Debit or Credit?
	Account         string  // 3rd party account number
	Amount          float64 //
	AccountTitle    string  // 3rd party (recipient) account name. up to 32 chars
	Reference       string  // payment ref. e.g "Invoice #1" up to 18 chars
	TraceBSB        string  // the transacting account BSB
	TraceAccount    string  // the transacting account number
	Remitter        string  // trhe transacting company name.
	TaxAmount       float64 //
}

type ABA struct {
	Header       Header
	Schema       []Schema
	Footer       Footer
	Transactions []Transaction
}

func (h *Header) toString() string {
	headerStr := fmt.Sprintf("0                 01%s       %s%s%s%s                                        ", h.Bank, h.User, h.UserNumber, h.Description, h.Date)
	return headerStr
}

func (f *Footer) toString() string {
	footerStr := fmt.Sprintf("7999-999            %s%s%s                        %s                                        ", f.NetTotal, f.CreditTotal, f.DebitTotal, f.NumberOfTransactions)
	return footerStr
}
